/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import metod.conexao;

/**
 *
 * @author Ezianne Monteiro
 */
public class alterarAlu extends javax.swing.JFrame {

    /**
     * Creates new form alterarAlu
     */
    public alterarAlu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cMat = new javax.swing.JTextField();
        cNome = new javax.swing.JTextField();
        cTurma = new javax.swing.JComboBox<>();
        cFaltas = new javax.swing.JTextField();
        alterar = new javax.swing.JButton();
        verAAlterar = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(542, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Alterar Dados do Aluno");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        tabela1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Matricula", "Nome Do Aluno", "Turma", "Faltas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 260, 240));

        jLabel2.setText("Matricula:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel3.setText("Nome:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel4.setText("Turma:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel5.setText("Faltas:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));
        getContentPane().add(cMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 130, -1));
        getContentPane().add(cNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 150, -1));

        cTurma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1° ANO", "2° ANO", "3° ANO" }));
        getContentPane().add(cTurma, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));
        getContentPane().add(cFaltas, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 40, -1));

        alterar.setText("Alterar");
        alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarActionPerformed(evt);
            }
        });
        getContentPane().add(alterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, -1));

        verAAlterar.setText("Ver Alunos");
        verAAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verAAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(verAAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verAAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verAAlterarActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = conexao.con();
            PreparedStatement ps = con.prepareStatement("select matricula, nome, turma, faltas from aluno");
            ResultSet res = ps.executeQuery();
            DefaultTableModel md = (DefaultTableModel) tabela1.getModel();
            while(tabela1.getRowCount()>0){
                md.removeRow(0);
            }
            while(res.next()){
                String[] itens = new String[]{String.valueOf(res.getInt("matricula")), res.getString("nome"),
                res.getString("turma"), String.valueOf(res.getInt("faltas"))};
                md.addRow(itens);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_verAAlterarActionPerformed

    private void alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = conexao.con();
            PreparedStatement pstmt = con.prepareStatement("update aluno set nome = ?, "
            + "turma = ?, "
            + "faltas = ? "
            + "where matricula = ?");
            pstmt.setString(1, cNome.getText());
            if(cTurma.getSelectedIndex()==0){
                pstmt.setString(2, "1° ANO");
            }else if(cTurma.getSelectedIndex()==1){
                pstmt.setString(2, "2° ANO");
            }else if(cTurma.getSelectedIndex()==2){
                pstmt.setString(2, "3° ANO");
            }
            pstmt.setInt(3, Integer.valueOf(cFaltas.getText()));
            pstmt.setInt(4, Integer.valueOf(cMat.getText()));
            int num = pstmt.executeUpdate();
            if(num>0){
                JOptionPane.showMessageDialog(null, "Dados alterados com sucesso!!",
                                    "Dados do Aluno", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null, "Algo ocorreu de errado", 
                        "Dados do Aluno", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(alterarAlu.class.getName()).log(Level.SEVERE, null, ex);
            ex.printStackTrace();
        }
    }//GEN-LAST:event_alterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(alterarAlu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(alterarAlu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(alterarAlu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(alterarAlu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new alterarAlu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterar;
    private javax.swing.JTextField cFaltas;
    private javax.swing.JTextField cMat;
    private javax.swing.JTextField cNome;
    private javax.swing.JComboBox<String> cTurma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela1;
    private javax.swing.JButton verAAlterar;
    // End of variables declaration//GEN-END:variables
}
