/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.Random;
import javax.swing.JOptionPane;
import metod.conexao;

/**
 *
 * @author Ezianne Monteiro
 */
public class cadastro extends javax.swing.JFrame {

    /**
     * Creates new form cadastro
     */
    public cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cNome = new javax.swing.JTextField();
        cDisc = new javax.swing.JTextField();
        cSenha = new javax.swing.JTextField();
        cadastrase = new javax.swing.JButton();
        cTurma = new javax.swing.JComboBox<>();

        setMinimumSize(new java.awt.Dimension(480, 360));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Cadastre-se aqui:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, -1, -1));

        jLabel4.setText("Disciplina:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        jLabel5.setText("Turmas:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, -1, -1));

        jLabel6.setText("Senha:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));

        jLabel7.setText("Digite uma senha coma até 6 numeros:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));
        getContentPane().add(cNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 170, -1));
        getContentPane().add(cDisc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 150, -1));
        getContentPane().add(cSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 170, -1));

        cadastrase.setText("Cadastrar-se");
        cadastrase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastraseActionPerformed(evt);
            }
        });
        getContentPane().add(cadastrase, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, -1, -1));

        cTurma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1° ANO", "2° ANO", "3° ANO" }));
        getContentPane().add(cTurma, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastraseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastraseActionPerformed
        // TODO add your handling code here:
        try {
            Connection con = conexao.con();
            PreparedStatement ps = con.prepareStatement("insert into professor values (?,?,?,?,?)");
            Random ran = new Random();
            String id1 = String.valueOf(ran.nextInt(9) + 1);
            String id2 = String.valueOf(ran.nextInt(10));
            String id3 = String.valueOf(ran.nextInt(10));
            String id = id1+id2+id3;
            ps.setInt(1, Integer.valueOf(id));
            ps.setString(2, cNome.getText());
            ps.setString(3, cDisc.getText());
            if(cTurma.getSelectedIndex()==0){
                ps.setString(4, "1° ANO");
            }else if(cTurma.getSelectedIndex()==1){
                ps.setString(4, "2° ANO");
            }else if(cTurma.getSelectedIndex()==2){
                ps.setString(4, "3° ANO");
            }
            ps.setString(5, cSenha.getText());
            
            int num = ps.executeUpdate();
            if(num>0){
                JOptionPane.showMessageDialog(null, "Cadastrado com sucesso! "
                        + "Esse é seu id: "+id+", use-o para acessar seu perfil",
                        "Mensagem de confirmação", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null, "Algo está errado no "
                        + "cadastro, verifique e tente novamente!!", "ERRO!!", 
                        JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_cadastraseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cDisc;
    private javax.swing.JTextField cNome;
    private javax.swing.JTextField cSenha;
    private javax.swing.JComboBox<String> cTurma;
    private javax.swing.JButton cadastrase;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
